# Generated by Django 5.2.13 on 2026-04-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'Blog'), (1, 'Forum')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (3, 'Hidden')], default=0),
        ),
    ]
