# Generated by Django 5.2.13 on 2026-04-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
