# Generated by Django 5.2.13 on 2026-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label_colour', models.CharField(choices=[('#D9BAAF', 'Beige'), ('#C3C2C2', 'Grey'), ('#A7CFFF', 'Blue'), ('#B6E2CF', 'Mint'), ('#77CCBB', 'Duckegg'), ('#26C6DA', 'Turquoise'), ('#0CCABA', 'Teal'), ('#2ECC70', 'Jade'), ('#33FF55', 'Green'), ('#A3D977', 'Lime'), ('#FFF0A7', 'Lemon'), ('#FFD54F', 'Yellow'), ('#FFC107', 'Amber'), ('#FF9800', 'Orange'), ('#FEAA8C', 'Salmon'), ('#FF8AB3', 'Rose'), ('#FF7DAF', 'Bubblegum'), ('#FF78FF', 'Pink'), ('#FFA8FF', 'Lilac'), ('#C7B6E2', 'Mauve')], default='#D9BAAF', unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.category'),
        ),
    ]
